export enum ErrorCode {
  SERVER_ERROR,
  UNKNOWN_ERROR,
  BAD_REQUEST,
  NOT_FOUND,
  PASSWORD_NOT_MATCH,
  JWT_NOT_DEFINED,
  UNAUTHORIZED,
  UNAUTHENTICATED,
  EXIST,
  NOT_EXIST,
  OVER_CAPACITY,
  TABLE_IN_USE,
  TABLE_CLOSED,
  TABLE_NOT_OPEN,
  ORDER_CLOSED,
  TRANSACTION_ALREADY_STARTED,
  PAYMENT_ALREADY_COMPLETED,
  SHIFT_NOT_OPEN,
  EMPLOYEE_SHIFT_NOT_OPEN,
  ALREADY_CLOCKED_IN,
  INACTIVE,
}

export const ErrorCodeResponse: Record<ErrorCode, { Code: number; Message: string; HttpCode: number }> = {
  [ErrorCode.SERVER_ERROR]: { Code: 1000, Message: "Server error", HttpCode: 500 },
  [ErrorCode.UNKNOWN_ERROR]: { Code: 999, Message: "Unknown error", HttpCode: 500 },
  [ErrorCode.BAD_REQUEST]: { Code: 101, Message: "Bad request", HttpCode: 400 },
  [ErrorCode.NOT_FOUND]: { Code: 102, Message: "Not found", HttpCode: 404 },
  [ErrorCode.PASSWORD_NOT_MATCH]: { Code: 103, Message: "Password not match", HttpCode: 400 },
  [ErrorCode.JWT_NOT_DEFINED]: { Code: 104, Message: "JWT not defined", HttpCode: 500 },
  [ErrorCode.UNAUTHORIZED]: { Code: 105, Message: "Unauthorized", HttpCode: 401 },
  [ErrorCode.UNAUTHENTICATED]: { Code: 106, Message: "Unauthenticated", HttpCode: 401 },
  [ErrorCode.EXIST]: { Code: 107, Message: "Already exists", HttpCode: 409 },
  [ErrorCode.NOT_EXIST]: { Code: 108, Message: "Does not exist", HttpCode: 404 },
  [ErrorCode.OVER_CAPACITY]: { Code: 109, Message: "Over capacity", HttpCode: 400 },
  [ErrorCode.TABLE_IN_USE]: { Code: 110, Message: "Table is currently in use", HttpCode: 400 },
  [ErrorCode.TABLE_CLOSED]: { Code: 111, Message: "Table is closed", HttpCode: 400 },
  [ErrorCode.TABLE_NOT_OPEN]: { Code: 112, Message: "Table is not open", HttpCode: 400 },
  [ErrorCode.ORDER_CLOSED]: { Code: 113, Message: "Order is closed", HttpCode: 400 },
  [ErrorCode.TRANSACTION_ALREADY_STARTED]: { Code: 114, Message: "Transaction already started", HttpCode: 400 },
  [ErrorCode.PAYMENT_ALREADY_COMPLETED]: { Code: 115, Message: "Payment already completed", HttpCode: 400 },
  [ErrorCode.SHIFT_NOT_OPEN]: { Code: 116, Message: "Shift is not open", HttpCode: 400 },
  [ErrorCode.EMPLOYEE_SHIFT_NOT_OPEN]: { Code: 117, Message: "Employee shift is not open", HttpCode: 400 },
  [ErrorCode.ALREADY_CLOCKED_IN]: { Code: 118, Message: "Employee is already clocked in", HttpCode: 400 },
  [ErrorCode.INACTIVE]: { Code: 119, Message: "Inactive", HttpCode: 400 },
}
